apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: eshopwebmvc
  name: eshopwebmvc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshopwebmvc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: eshopwebmvc
    spec:
      containers:
        - image: pdetender/eshopwebmvc
          name: eshopwebmvc
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
      restartPolicy: Always
status: {}
