apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: eshoppublicapi
  name: eshoppublicapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshoppublicapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: eshoppublicapi
    spec:
      containers:
        - image: eshoppublicapi
          name: eshoppublicapi
          resources: {}
      restartPolicy: Always
status: {}
